main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /team

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

