# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    _defaults:
        autowire: true
        autoconfigure: true
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    main.twig.config_extension:
        class: MainBundle\Twig\ConfigExtension
        arguments:
            $doctrine: "@doctrine"
            $kernel: "@kernel"
        tags:
            - { name: twig.extension }

    admin.twig.synergie_extension:
        class: AdminBundle\Twig\SynergieExtension
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    admin.twig.team:
        class: AdminBundle\Twig\TeamExtension
        arguments:
            $doctrine: "@doctrine"
            $controlTeam: "@team.control_team"
        tags:
            - { name: twig.extension }

    main.twig.remove_accent_extension:
        class: MainBundle\Twig\RemoveAccentExtension
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        arguments:
            - "@translator.default"
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    team.control_team:
        class: TeamBundle\Utils\ControlTeam
        arguments: ['@doctrine.orm.entity_manager']

    match.control_match:
        class: MatchBundle\Utils\ControlMatch
        arguments: ['@doctrine.orm.entity_manager', '@team.control_team']

    notification.notification:
        class: NotificationBundle\Utils\NotificationService
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    doctrine.listener:
        class: MainBundle\Listener\DoctrineListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: onFlush, method: onFlush }

twig:
    globals:
        notification: "@notification.notification"
